db.url=jdbc:postgresql://localhost:5432/testdb
db.user=postgres
db.password=postgres
db.driver.name=org.postgresql.Driver

# jdbcUrl=jdbc:postgresql://localhost:5432/testdb
# username=postgres
# password=postgres
# driverClassName=org.postgresql.Driver